/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meeting } from './Meeting';
import {
    MeetingFromJSON,
    MeetingFromJSONTyped,
    MeetingToJSON,
} from './Meeting';

/**
 * 
 * @export
 * @interface CreateAttendanceReq
 */
export interface CreateAttendanceReq {
    /**
     * 
     * @type {Array<Array<Array<any>>>}
     * @memberof CreateAttendanceReq
     */
    content: Array<Array<Array<any>>>;
    /**
     * 
     * @type {Array<Meeting>}
     * @memberof CreateAttendanceReq
     */
    meetings: Array<Meeting>;
}

/**
 * Check if a given object implements the CreateAttendanceReq interface.
 */
export function instanceOfCreateAttendanceReq(value: object): boolean {
    if (!('content' in value)) return false;
    if (!('meetings' in value)) return false;
    return true;
}

export function CreateAttendanceReqFromJSON(json: any): CreateAttendanceReq {
    return CreateAttendanceReqFromJSONTyped(json, false);
}

export function CreateAttendanceReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAttendanceReq {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'meetings': ((json['meetings'] as Array<any>).map(MeetingFromJSON)),
    };
}

export function CreateAttendanceReqToJSON(value?: CreateAttendanceReq | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
        'meetings': ((value['meetings'] as Array<any>).map(MeetingToJSON)),
    };
}

