/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Meta
 */
export interface Meta {
    /**
     * 
     * @type {string}
     * @memberof Meta
     */
    schoolName: string;
    /**
     * 
     * @type {string}
     * @memberof Meta
     */
    schoolId: string;
}

/**
 * Check if a given object implements the Meta interface.
 */
export function instanceOfMeta(value: object): boolean {
    if (!('schoolName' in value)) return false;
    if (!('schoolId' in value)) return false;
    return true;
}

export function MetaFromJSON(json: any): Meta {
    return MetaFromJSONTyped(json, false);
}

export function MetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Meta {
    if (json == null) {
        return json;
    }
    return {
        
        'schoolName': json['school_name'],
        'schoolId': json['school_id'],
    };
}

export function MetaToJSON(value?: Meta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'school_name': value['schoolName'],
        'school_id': value['schoolId'],
    };
}

