/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Timeslot
 */
export interface Timeslot {
    /**
     * 
     * @type {number}
     * @memberof Timeslot
     */
    day: number;
    /**
     * 
     * @type {Date}
     * @memberof Timeslot
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof Timeslot
     */
    endTime: Date;
    /**
     * 
     * @type {number}
     * @memberof Timeslot
     */
    timeslotNumber: number;
    /**
     * 
     * @type {string}
     * @memberof Timeslot
     */
    timeslotType: TimeslotTimeslotTypeEnum;
}


/**
 * @export
 */
export const TimeslotTimeslotTypeEnum = {
    Lecture: 'lecture',
    OfficeWork: 'office_work',
    Other: 'other'
} as const;
export type TimeslotTimeslotTypeEnum = typeof TimeslotTimeslotTypeEnum[keyof typeof TimeslotTimeslotTypeEnum];


/**
 * Check if a given object implements the Timeslot interface.
 */
export function instanceOfTimeslot(value: object): boolean {
    if (!('day' in value)) return false;
    if (!('startTime' in value)) return false;
    if (!('endTime' in value)) return false;
    if (!('timeslotNumber' in value)) return false;
    if (!('timeslotType' in value)) return false;
    return true;
}

export function TimeslotFromJSON(json: any): Timeslot {
    return TimeslotFromJSONTyped(json, false);
}

export function TimeslotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Timeslot {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'],
        'startTime': (new Date(json['start_time'])),
        'endTime': (new Date(json['end_time'])),
        'timeslotNumber': json['timeslot_number'],
        'timeslotType': json['timeslot_type'],
    };
}

export function TimeslotToJSON(value?: Timeslot | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'day': value['day'],
        'start_time': ((value['startTime']).toISOString()),
        'end_time': ((value['endTime']).toISOString()),
        'timeslot_number': value['timeslotNumber'],
        'timeslot_type': value['timeslotType'],
    };
}

