/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeslotJS
 */
export interface TimeslotJS {
    /**
     * 
     * @type {number}
     * @memberof TimeslotJS
     */
    year: number;
    /**
     * 
     * @type {number}
     * @memberof TimeslotJS
     */
    month: number;
    /**
     * 
     * @type {number}
     * @memberof TimeslotJS
     */
    day: number;
    /**
     * 
     * @type {number}
     * @memberof TimeslotJS
     */
    timeslotNumber: number;
    /**
     * 
     * @type {string}
     * @memberof TimeslotJS
     */
    timeslotType: TimeslotJSTimeslotTypeEnum;
}


/**
 * @export
 */
export const TimeslotJSTimeslotTypeEnum = {
    Lecture: 'lecture',
    OfficeWork: 'office_work',
    Other: 'other'
} as const;
export type TimeslotJSTimeslotTypeEnum = typeof TimeslotJSTimeslotTypeEnum[keyof typeof TimeslotJSTimeslotTypeEnum];


/**
 * Check if a given object implements the TimeslotJS interface.
 */
export function instanceOfTimeslotJS(value: object): boolean {
    if (!('year' in value)) return false;
    if (!('month' in value)) return false;
    if (!('day' in value)) return false;
    if (!('timeslotNumber' in value)) return false;
    if (!('timeslotType' in value)) return false;
    return true;
}

export function TimeslotJSFromJSON(json: any): TimeslotJS {
    return TimeslotJSFromJSONTyped(json, false);
}

export function TimeslotJSFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeslotJS {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'],
        'month': json['month'],
        'day': json['day'],
        'timeslotNumber': json['timeslot_number'],
        'timeslotType': json['timeslot_type'],
    };
}

export function TimeslotJSToJSON(value?: TimeslotJS | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'year': value['year'],
        'month': value['month'],
        'day': value['day'],
        'timeslot_number': value['timeslotNumber'],
        'timeslot_type': value['timeslotType'],
    };
}

