/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeslotJS } from './TimeslotJS';
import {
    TimeslotJSFromJSON,
    TimeslotJSFromJSONTyped,
    TimeslotJSToJSON,
} from './TimeslotJS';
import type { Teacher } from './Teacher';
import {
    TeacherFromJSON,
    TeacherFromJSONTyped,
    TeacherToJSON,
} from './Teacher';

/**
 * 
 * @export
 * @interface UpdateAttendanceReq
 */
export interface UpdateAttendanceReq {
    /**
     * 
     * @type {Array<TimeslotJS>}
     * @memberof UpdateAttendanceReq
     */
    timeslotJsList: Array<TimeslotJS>;
    /**
     * 
     * @type {number}
     * @memberof UpdateAttendanceReq
     */
    extraPayment: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateAttendanceReq
     */
    remark: string;
    /**
     * 
     * @type {Teacher}
     * @memberof UpdateAttendanceReq
     */
    teacher: Teacher;
}

/**
 * Check if a given object implements the UpdateAttendanceReq interface.
 */
export function instanceOfUpdateAttendanceReq(value: object): boolean {
    if (!('timeslotJsList' in value)) return false;
    if (!('extraPayment' in value)) return false;
    if (!('remark' in value)) return false;
    if (!('teacher' in value)) return false;
    return true;
}

export function UpdateAttendanceReqFromJSON(json: any): UpdateAttendanceReq {
    return UpdateAttendanceReqFromJSONTyped(json, false);
}

export function UpdateAttendanceReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAttendanceReq {
    if (json == null) {
        return json;
    }
    return {
        
        'timeslotJsList': ((json['timeslot_js_list'] as Array<any>).map(TimeslotJSFromJSON)),
        'extraPayment': json['extra_payment'],
        'remark': json['remark'],
        'teacher': TeacherFromJSON(json['teacher']),
    };
}

export function UpdateAttendanceReqToJSON(value?: UpdateAttendanceReq | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'timeslot_js_list': ((value['timeslotJsList'] as Array<any>).map(TimeslotJSToJSON)),
        'extra_payment': value['extraPayment'],
        'remark': value['remark'],
        'teacher': TeacherToJSON(value['teacher']),
    };
}

